token:
  expiration_time: 864000000 
  secret: '{cipher}AYBxDbRhI9sAAi9X+avmsC0Lpx6EkCRyoCrEWbr9+TE5Rl3ZNKQTWicgdWMArFNWfeCZNt2H7hrkiucB05CaRFYnzikmu15INbhLWO+mQEz8ZaPInfEN3cQDl2OsGuQn9VX0oaRaYkbS4303aECE2fRqRZOSzusfw2NLm2sdas1k1cwerITUGBoUVhfHPrbRBiWPduaha4ze3T8W0AHB0Hwu4DYxXISs0YmJm/yexjUhcwZjO6AXkWNhlbu9dIff7ieCFSGj5jEfgYWq7tmzHxRwYAagL+QBy3CdfFZTPAztzFpApmMh6OkYGuQoUDiIMdcYjC017SFrYvRujQSAqMkuh0dQaLq61TRBD1CdF9AhJfuscYgfIY4sUiM/aKwxyejmiCSpWc42IDGvxxBXjvFOGafLSsk196bvHqaagQKq+0S2uv3v+ozV+UWjOseaAZ7U9bxgdKh03D2jYA+x2yuRRbkw6z1bEl+lDdfr2EPX8BEZZPMhmbYul8S+bqyWauzBR5LXBffABxt/HeNmexWu3NESp3irqeeJQR95jVBs+LaaWaa9twK7/HFBhi6eOgxzywlcajOsxKD8qcMumbSlbLq4fGQhvwrmBZRTTMRFueGm3M+k0X+CUn7BPkrz0A8='

gateway:
  ip: 172.18.0.1
